apiVersion: skaffold/v2beta24
kind: Config
build:
  local:
    concurrency: 3
    useBuildkit: true
  artifacts:
    - image: kubesail/pibox-io
      context: .
      sync:
        manual:
          - src: '**/*'
            dest: .
profiles:
  - name: dev
    build:
      artifacts:
        - image: kubesail/pibox-io
          sync:
            manual:
              - src: '**/*'
                dest: .
          docker:
            target: dev
  - name: prod
    build:
      artifacts:
        - image: kubesail/pibox-io
          docker:
            target: runner
    deploy:
      kustomize:
        paths:
          - k8s/prod
deploy:
  kustomize:
    paths:
      - k8s/base
  statusCheckDeadlineSeconds: 180
portForward:
  - resourceType: Service
    resourceName: pibox-io
    port: 3000
    address: 0.0.0.0
    localPort: 3000
