---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pibox-io
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 2
  template:
    spec:
      containers:
        - name: pibox-io
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: NEXT_PUBLIC_STRIPE_PUBLIC_KEY
              value: "pk_live_B2ylJU30kGz2y0k20LHiZhA7"
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   httpGet:
          #     path: /
          #     port: https-ports
          #     scheme: HTTP
          #     httpHeaders:
          #       - name: Host
          #         value: pibox.io
